### PR TITLE
Bump runtime to 20.08

### PR DESCRIPTION
**Pull request by nanonyme**

### CODE REVIEW

**Comment by nanonyme** [comment]
Complains about missing 128x128 icon.....

**Comment by bilelmoussaoui** [comment]
Hmm we should probably disable the icon check if it's a cli app, meanwhile you can add ` "skip-icons-check": true` to flathub.json

**Comment by nanonyme** [comment]
@bilelmoussaoui added flathub.json with icon check skip. Build seems to pass now.

**Comment by nanonyme** [comment]
@bilelmoussaoui any chance getting this integrated?

**Comment by bilelmoussaoui** [comment]
As I don't really use mosh, I will trust your tests and merge it.

**Comment by bilelmoussaoui** [comment]
Would you be interested in having write access to the repository as you seem to use it? :)

**Comment by nanonyme** [comment]
Sure.

**Comment by bilelmoussaoui** [comment]
Done, thanks!

**Comment by nanonyme** [comment]
Tested on x86_64, works for me. I don't have hardware to test on aarch64 but seems to build fine there too...

**Pull request merged**
